theme: jekyll-theme-architect

title: [Java EE Platform Specification]
description: [Project for the Java EE Expert Group]

# sidebar links url
links:
  download: https://jcp.org/en/jsr/detail?id=366
  source: https://github.com/javaee/javaee-spec
  license: LICENSE
  issues_url: site.github.issues_url # project's issue tracker
  mailinglist: https://javaee.groups.io/g/javaee-spec
  javadocs: javadocs
  #docs:
  #faq:

